### ISSUE TITLE
get an error while sending a body on DELETE method

### ISSUE THREAD

**Issue by resession** [RangerMauve/make-fetch#2]
when i use the DELETE method and send data inside the body, i get this error

node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at new NodeError (node:internal/errors:371:5)
    at Function.from (node:buffer:322:9)
    at bodyToIterator (F:\Proj\Research\gunfetch\node_modules\fetch-request-body-to-async-iterator\index.js:50:30)
    at fetch (F:\Proj\Research\gunfetch\node_modules\make-fetch\index.js:28:28)
    at fetch (F:\Proj\Research\gunfetch\node_modules\make-fetch\index.js:10:14)
    at test (F:\Proj\Research\gunfetch\app.js:36:22)
    at Object.<anonymous> (F:\Proj\Research\gunfetch\app.js:41:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by RangerMauve** [comment]
Would you be able to provide a minimal test case for this issue? Like a github repo that's got just enough code to show how this error works without extra libraries.

**Comment by resession** [comment]
ignore this issue, i will be closing it. the error was because i was not using make-fetch correctly. after some changes, it is working now.

**Comment by RangerMauve** [comment]
Glad you figured it out. 🎉
