### ISSUE TITLE
keep getting error

### ISSUE THREAD

**Issue by resession** [RangerMauve/make-fetch#6]
i am using the readme example but is keep getting the following error
```
TypeError: Failed to parse URL from [object Object]
    at new Request (node:internal/deps/undici/undici:9474:19)
    at fetch (file:///F:/Proj/Production/hybrid-browser/node_modules/make-fetch/index.js:11:21)
    at AsyncFunction.protocolHandler (F:\Proj\Production\hybrid-browser\app\protocols\fetch-to-handler.js:32:30) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:393:5)
      at URL.onParseError (node:internal/url:565:9)
      at new URL (node:internal/url:645:5)
      at new Request (node:internal/deps/undici/undici:9472:25)
      at fetch (file:///F:/Proj/Production/hybrid-browser/node_modules/make-fetch/index.js:11:21)
      at AsyncFunction.protocolHandler (F:\Proj\Production\hybrid-browser\app\protocols\fetch-to-handler.js:32:30) {
    input: '[object Object]',
    code: 'ERR_INVALID_URL'
  }
}
```

**Comment by resession** [comment]
i'll try the routed way and see if i can make it work
